### ISSUE TITLE
be more flexible about the web server selection options

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#14]
The web server selection process should include an "other" option, in which the user can enter the full name of an npm module to load as their web server. This is probably a rare occurrence, but it should be supported. e.g. in the case of private npm modules, their module can't use the trailpack-  prefix.

re: https://github.com/trailsjs/generator-trails/pull/13#discussion-diff-48322463R11

- [ ] create milestones and assign to 1.0-final

**Comment by jaumard** [comment]
:+1: same for template engine https://github.com/trailsjs/generator-trails/pull/11 cause there only jade/handelbars for now but with trailpack-express4 more are supported (ejs, mustache...) full list here https://www.npmjs.com/package/consolidate

**Comment by jaumard** [comment]
Need to merge this PR https://github.com/trailsjs/generator-trails/pull/15 (and maybe this one too https://github.com/trailsjs/generator-trails/pull/11) and after I can do this :)

**Comment by jaumard** [comment]
Closing this cause web server 'other' choice is available on last npm version
