### ISSUE TITLE
Trailpacks should have a way to generate files into the main application when installed

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#21]
It'd be a more generalized version of https://github.com/trailsjs/generator-trails/pull/15

**Comment by jaumard** [comment]
I see multiple way to do this : 

- Add command `yo trails:trailpack trailpackName` that install and copy archetype
- Change `trailpack-core` to add a model (or maybe just a json file if user don't use database) to keep trailpack status and if there no status it copy archetype and set status to `initialized`. Advantages if devs doesn't use generator to install trailpacks archetypes can be copied.

**Comment by jaumard** [comment]
Another way for doing this is to add a `postinstall` script (under trailpack repo) that copy trailpack `archetype` under main application. Generator-trailpack have to add this script under `package.json` when generate a new trailpack.

**Comment by jaumard** [comment]
So it's a start, for now with the last version of the generator we can do : 

`yo trails --trailpacks=trailpack-hapi,trailpack-gulp,trailpack-webpack`

But it will be better if archetype can be install without the generator.

**Comment by jaumard** [comment]
@tjwebb can I close this ? Generator install now all archetype files from trailpacks
