### ISSUE TITLE
Remove "files" property from generated package.json

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#28]
Confusingly,  npm *only* publishes the folders listed in the files array.

**Comment by tjwebb** [comment]
This must be added somewhere by the generator-node project...

**Comment by jaumard** [comment]
You're right I think it's here https://github.com/trailsjs/generator-node/blob/master/generators/app/index.js#L195 ?

**Comment by tjwebb** [comment]
resolved: https://github.com/trailsjs/generator-node/commit/2e5730ae5cd4a4183673339e52866ffe209f4a40

**Comment by tjwebb** [comment]
I just generated a new project, and this is still happening somehow. Opening until I can confirm resolution again.

**Comment by jaumard** [comment]
Are you sure @tjwebb  ? I didn't have it on new project...

**Comment by jaumard** [comment]
I just test with last version didn't see `files` on `package.json`. Feel free to reopen again if you have it.
