### ISSUE TITLE
"unit" tests should not test anything involving global.app

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#29]

**Comment by jaumard** [comment]
global.app is not use under `unit` tests, they only test file creation. Can you explain more what do you want here please ?

**Comment by jaumard** [comment]
@tjwebb up here :) thanks

**Comment by jaumard** [comment]
Colles by https://github.com/trailsjs/generator-trails/commit/1f48ef8f3554061e05bd32ab4342e562628c1ac6
