### ISSUE TITLE
place .eslintrc in test/ dir to customize testing rules

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#3]
re https://github.com/trailsjs/eslint-config-trails/issues/7

**Comment by wbprice** [comment]
Add an `.eslintrc` containing at least 
```
{
  "extends": "trails/test"
}
```
to the test directory and it will grab test-specific linting rules after https://github.com/trailsjs/eslint-config-trails/issues/7 is closed.

**Comment by tjwebb** [comment]
PRs are welcome ;)

**Comment by konstantinzolotarev** [comment]
@tjwebb @wbprice What about new EsLint version and deprecated .eslintrc ?
http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by jaumard** [comment]
Closing this. I merge @wbprice PR and also rename his file to .eslintrc.json into PR https://github.com/trailsjs/generator-trails/pull/16 cause you're right .eslintrc is deprecated
