### ISSUE TITLE
test folder should include mocha.opts and eslintrc.json

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#30]

**Comment by jaumard** [comment]
Hum already the case isn't it ? 
https://github.com/trailsjs/generator-trails/blob/master/test/.eslintrc.json
https://github.com/trailsjs/generator-trails/blob/master/test/mocha.opts

**Comment by tjwebb** [comment]
I think I meant to file this under generator-trailpack. Sorry about that.

**Comment by jaumard** [comment]
No problem :) but there same files under generator-trailpack too lol  
https://github.com/trailsjs/generator-trailpack/blob/master/test/mocha.opts
https://github.com/trailsjs/generator-trailpack/blob/master/test/.eslintrc.json

**Comment by jaumard** [comment]
Closing this because files are present. Let me know if I'm wrong

**Comment by tjwebb** [comment]
Yes I think I resolved this awhile back but did not close this issue. Thank you.
