### ISSUE TITLE
--coffee, --litcoffee etc. otpions

### ISSUE THREAD

**Issue by scippio** [trailsjs/generator-trails#33]
It will be possible added this options? I can add pull requests in the future for gen. templates...

**Comment by jaumard** [comment]
I didn't know at all coffee or litcoffee but Trails use js ES2015 so it is not enough ? 
The team take position to don't have any coffee on official modules https://github.com/trailsjs/trails/blob/382a768231c33144b127c31caae09597eabc04b3/CONTRIBUTING.md#no-coffeescript 
I let them answer you about this officially.

**Comment by scippio** [comment]
Hmm ok... :( but I liked a coffee code generated user controllers/services etc.. (not core things). if they don't like it.. nevermind, I can create something like generator-trails-coffee... :)

**Comment by tjwebb** [comment]
My position is that es6/es7 should always be preferred over non-native implementations such as CoffeeScript. If you really want to use coffeescript, I think that needs to be built as an addon.

**Comment by jaumard** [comment]
I'm closing this as there will be no official work on this feature. Like Travis say, let us know when you have something working with coffee.
