### ISSUE TITLE
Web.js ignored with beta-1 version

### ISSUE THREAD

**Issue by jaumard** [trailsjs/generator-trails#37]
Now web.js is copied from web server trailpack. So there some conflict on the `config/index.js` and some files are not added it can be the web.js but it can another config file from a trailpack choose on the generator.

First though : One way to resolve this is to rebuild index.js after all trailpacks was installed. 

Related to https://github.com/trailsjs/trails/issues/149

**Comment by jdell64** [comment]
I ran the generator and this only seems to be an issue with hapi? with express, it asks if you want to overwrite some files. If you say 'no' to this, it works fine.

**Comment by jaumard** [comment]
yes it's only with hapi because it doesn't yet embed the `web.js` file. Express does :)

**Comment by jdell64** [comment]
oh, nm :dash:

**Comment by jaumard** [comment]
@jdell64 thanks ! I just fix it here https://github.com/trailsjs/trailpack-express4/pull/12
