### ISSUE TITLE
Generated package.json uses old dependencies

### ISSUE THREAD

**Issue by LobeTia** [trailsjs/generator-trails#58]
Hello, I've a doubt about the generated dependencies

I'm using generator-trails@1.0.11 

Generating a new trails app with this setting

    ? Choose a Web Server express
    ? What express version do you want to use ? 4
    ? Choose an ORM sequelize
    ? Do you want to use Footprints (automatic REST API from models) ? No
    ? Module Name heroku-trails-test
    ? Description 
    ? Project homepage url 
    ? Author's Name Mattia Lobertini <lobetia@gmail.com>
    ? Author's Email lobetia@gmail.com
    ? Author's Homepage 
    ? Package keywords (comma to split) 
    ? GitHub username or organization 
    ? Which license do you want to use? MIT

Will write this dependencies in package.json

    "dependencies": {
        ...
        "trailpack-core": "^1.0.0-beta-3",
        "trailpack-express": "^1.0.1",
        "trailpack-repl": "^1.0.0-beta-3",
        "trailpack-router": "^1.0.0-beta-4",
        "trailpack-sequelize": "^1.0.0",
        "trails": "^1.0.0-beta-1",
        "trails-controller": "^1.0.0-beta-2",
        "trails-model": "^1.0.0-beta-2",
        "trails-policy": "^1.0.1",
        "trails-service": "1.0.0-beta-2",
        ...
     }

A lot of dep seems outdated, it's a desired behavior?

**Comment by jaumard** [comment]
A bug is already open about this here https://github.com/trailsjs/trails/issues/195 :) don't hesitate to give us your feedback about it
