### ISSUE TITLE
dependencies are missed in package.json

### ISSUE THREAD

**Issue by lolenko** [trailsjs/generator-trails#63]
after i generate trails app i have 
```  packs: [
    require('trailpack-core'),
    require('trailpack-repl'),
    require('trailpack-router'),
    require('trailpack-hapi'), 
require('trailpack-waterline'), 
require('trailpack-footprints')
  ],```
in main.js , but don't have required trailpacks in package.json
`  "dependencies": {
    "trailpack-core": "^1.0.0-beta-3",
    "trailpack-repl": "^1.0.0-beta-3",
    "trailpack-router": "^1.0.0-beta-4",
    "trails": "^1.0.0-beta-1",
    "trails-controller": "^1.0.0-beta-2",
    "trails-model": "^1.0.0-beta-2",
    "trails-policy": "^1.0.1",
    "trails-service": "1.0.0-beta-2",
    "winston": "^2.2"
  },`

so first npm start is following by errors((

**Comment by lolenko** [comment]
After I install all missed packages, i get next error `Cannot find module './controllers'`

**Comment by lolenko** [comment]
Sorry, i've update yo

**Comment by lolenko** [comment]
Anyway, when i choose the express as a server, i get those errors( i mentioned above
I have no controllers and polices folders, also missed trailspack-express dependency in package.json

**Comment by lolenko** [comment]
Anyway, when i choose the express as a server, i get those errors( i mentioned above
I have no controllers and polices folders, also missed trailspack-express dependency in package.json

**Comment by jaumard** [comment]
Hi @lolenko,
What's your yo, node and npm version ? Witch OS ? I can't reproduce

**Comment by lolenko** [comment]
node v4.4.7
npm 3.10.6
yo 1.8.4
OS X El Capitan 10.11.4

**Comment by lolenko** [comment]
hmm, i generated 5 times in the morning. But now all is OK.

**Comment by konstantinzolotarev** [comment]
@lolenko Ok for close an issue ?

**Comment by lolenko** [comment]
ок
