### ISSUE TITLE
views config documentation link gives 403 Forbidden

### ISSUE THREAD

**Issue by connor11528** [trailsjs/generator-trails#64]
I see there was discussion in #8 about template engines. It would be very helpful to have some documentation about where the views files go. 

In **config/views.js** the comments point to `http://trailsjs.io/doc/config/views.js` but that goes nowhere and is not helpful. Where should templates go and what should the config object look like?

![screen shot 2016-07-15 at 10 20 20 pm](https://cloud.githubusercontent.com/assets/3578908/16892948/65c4abae-4ada-11e6-9511-ed5c6e40e8d6.png)

**Comment by jaumard** [comment]
@connor11528 documentation is not online yet, they are placeholder. Only on trails-docs repo for now. 
For views configuration you can see config here for express (https://github.com/trailsjs/trailpack-express#view-config) and here for hapi (https://github.com/trailsjs/trailpack-hapi#view-config). 
This issue should be here anyway so I'm closing it :) feel free to open one on trails-docs or trails but docs will be online only when it will be finish.
Thanks :)

**Comment by connor11528** [comment]
is there any timeline or road map for documentation? I don't see any notes on the [trail map](https://github.com/trailsjs/trails/blob/master/ROADMAP.md).

The trails docs repo is very sparse. I created an [issue](https://github.com/trailsjs/trails-docs/issues/16) and a [PR#15](https://github.com/trailsjs/trails-docs/pull/15) to get this started but haven't got any love.

Thank you for the trailpack-express link though! I will look at that repo to help me get started

**Comment by scott-wyatt** [comment]
@connor11528 I was in the same boat and people are working hard to get documentation available.  What I found the most helpful in the mean time, was building my own trailpack.  It's not ideal, but it's a great way to learn the ins and outs.  Trails is also very small code base comparably speaking, you could almost go through it line by line in an afternoon and then you could help write docs :-)

**Comment by connor11528** [comment]
Okay rad. Yeah excited to be part of the growing project. Will dig deeper and speak up when encounter issues

I think next steps are to create a trailpack (perhaps for authentication cause that's crucial) and also check out the express link @jaumard provided above

**Comment by maissani** [comment]
Hi @connor11528 , @jaumard have already made an authentication trailpack here, have a look threre: https://github.com/jaumard/trailpack-passport. 
Your "dig deeper" makes me think about Shaun T (From Insanity workout training). 
Any help on docs is welcome.

**Comment by connor11528** [comment]
haha for sure. Maybe the trailpack-passport should be under the trailsjs account? I searched trails-auth and found this empty repo: https://github.com/trailsjs/trailpack-auth

Glad there's an auth module out there already! Thank you

**Comment by jaumard** [comment]
@connor11528 trailpack-passport only work with Express and some ORM, that's why I didn't add it under trails account :).
