### ISSUE TITLE
Name of create policy is not consistant

### ISSUE THREAD

**Issue by KevinNTH** [trailsjs/generator-trails#65]
Hi, 

When I create a Policy with `yo` : `yo trails:policy Auth` or `yo trails:policy AuthPolicy`, it's create me a file named `api/policies/Auth.js` with `AuthPolicy` class. In `api/policies/index.js`, I have `exports.Auth = require('./Auth')`.

So to use my policy : 
```js
// config/policies.js
module.exports = {
  ExampleController: {
    test: [ 'Auth.test' ] // Should be AuthPolicy.test
  }
}
```

But in the example (readme.md) there is :
```js
// config/policies.js
module.exports = {
  ExampleController: {
    test: [ 'ExamplePolicy.test' ]
  }
}
```

I find this is not consistent regarding to the `controllers` and `services` system which add `Controller` and `Service` prefix to the new generated controller or service. So when I generate a policy, I should have `AuthPolicy.js` instead of `Auth.js` isn't it ?

**The same note applies to `models` too**.

**Comment by konstantinzolotarev** [comment]
Fix here: https://github.com/trailsjs/generator-util/pull/3

**Comment by KevinNTH** [comment]
Thanks for the fix @konstantinzolotarev :)
I had mentionned the **models** too :)

**Comment by jaumard** [comment]
@KevinNTH models are working like they should, they are native to ORM so we don't want to add `Model` suffix at the end (because most ORM will also add it into the table name)
Thanks @konstantinzolotarev ! Waiting travisCI results and I merge it :D
