### ISSUE TITLE
Selecting: bookshelf (not supported yet)

### ISSUE THREAD

**Issue by Bwen** [trailsjs/generator-trails#67]
Is it normal its showing the following in the config/main.js after selecting _bookshelf (not supported yet)_
![alt text](http://i.imgur.com/jebFUF4.png)

**Comment by konstantinzolotarev** [comment]
@Bwen working on a fix

**Comment by jaumard** [comment]
There a problem with Trails, it doesn't stop successfully :( then when other tests try to start a new Trails port 3000 is already in use so tests fail https://ci.appveyor.com/project/trailsjs/generator-trails/build/1.0.47/job/4gbiuish4l6s0pi5#L616
