### ISSUE TITLE
Mocha tests should not use arrow functions

### ISSUE THREAD

**Issue by iwritesomecode** [trailsjs/generator-trails#69]
From [Mocha Docs](http://mochajs.org/#arrow-functions):

> Passing arrow functions (“lambdas”) to Mocha is discouraged. Due to the lexical binding of this, such functions are unable to access the Mocha context. For example, the following code will fail due to the nature of lambdas:

```
describe('my suite', () => {
  it('my test', () => {
    // should set the timeout of this test to 1000 ms; instead will fail
    this.timeout(1000);
    assert.ok(true);
  });
});
```

I'm thinking particularly of the templates for things like services, policies, etc.

**Comment by konstantinzolotarev** [comment]
@metzuda it really depends on need. 
In most cases there is no real need to use mocha context at all. And creating pure functions not really needed. But with arrow functions tests becomes a bit cleaner.

@trailsjs/maintainers Any opinion on this ?

**Comment by metzuda** [comment]
@konstantinzolotarev granted, the whole reason I noticed this was because I _did_ need mocha context for tests, and noticed that they were all set up as arrow functions, which seems to be a purely style issue, here.

**Comment by tjwebb** [comment]
Crap, I use arrow functions everywhere in mocha. **_everywhere_**. Is there a larger discussion to be had about whether this is a bad idea?

**Comment by iwritesomecode** [comment]
I'm not really sure. Within most Trails' modules it doesn't look like it's an issue, and I don't think it's something that most people will run into — on the other hand, I feel like encouraging what may end up being a bad habit just because we like arrow functions.

If someone has to go through and re-write a bunch of generated tests then the generator has actually cost them time. Better to be safe out of the box, I say.

**Comment by ryanwilliamquinn** [comment]
I think it is only an issue if you ever need to use `this`, which is rare, and can be handled as a one-off.

**Comment by jaumard** [comment]
Closing this, in the generator itself we don't care. If it's a problem for generate class, issue should be create on Trails repo (it contains sources that are copy by this generator)
