### ISSUE TITLE
generator should not require email

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#73]
re: https://github.com/trailsjs/doc/issues/26

**Comment by jaumard** [comment]
I think with my current PR, it will not ask the email at all... because I remove the generator-node totally. So it will not ask for basic package.json info. If we want them, I think it will be better to add questions instead of use generator-node witch generate some trouble since the beginning

**Comment by jaumard** [comment]
Fixed in https://github.com/trailsjs/generator-trails/pull/72
